import Head from 'next/head'
import Image from 'next/image'

const HomePage = () => {
  return (
    <div>
      <Head>
        <title>Jack's Journal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Jack's Journal</h1>
      </main>

      <footer>
      </footer>
    </div>
  )
}

export default HomePage;
