import Head from "next/head";
import styled from "styled-components";
import Sidebar from "../components/sidebar";
import JournalEditor from "../components/journal-editor";
import { useState } from "react";

const Main = styled.main`
  display: flex;
  min-height: 100vh;
  min-width: 100vw;
`;

const Title = styled.h1`
  text-align: center;
  font-family: "Dancing Script", cursive;
  font-size: 2.5em;
`;

const ContentContainer = styled.div`
  flex-grow: 1;
  display: flex;
  flex-direction: column;
  overflow: auto;
  align-items: center;
  padding: 1em;
`;

const EditorContainer = styled.section`
  flex-grow: 1;
  width: 100%;
  max-width: 1200px;
  display: flex;
  flex-direction: column;
  gap: 0;
  box-shadow: 0px 0px 10px 4px rgba(0, 0, 0, 0.2);
  border-radius: 3px;
  background: white;
`;

const SaveButton = styled.button`
  width: 100%;
  margin-top: 0;
  border: none;
  padding: 0.6em;
  border-radius: 0 0 3px 3px;
  background-color: var(--bg-colour-secondary);
  color: var(--text-colour-secondary);
  font-size: 1.9em;
  transition: all 0.15s ease-in-out;
  transition: transform 0.07s ease-in-out;

  &:hover,
  &:active,
  &:focus {
    background-color: #00515d;
  }

  &:active {
    transform: translateY(2px);
  }
`;

const HomePage = () => {
  const [value, setValue] = useState("");

  const saveEntry = async () => {
    const response = await fetch("api/save-entry", {
      method: "POST",
      body: JSON.stringify({ file: btoa(value) }),
    });

    if (response.ok) {
      console.log(await response.json());
    } else {
      console.error(response);
      response.json().then((body) => console.log(body));
    }
  };

  return (
    <>
      <Head>
        <title>Jack's Journal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@700&display=swap"
          rel="stylesheet"
        />
      </Head>

      <Main>
        <aside>
          <Sidebar />
        </aside>

        <ContentContainer>
          <Title>Jack's Journal</Title>

          <EditorContainer>
            <JournalEditor value={value} setValue={setValue} />

            <SaveButton onClick={() => saveEntry()}>Save</SaveButton>
          </EditorContainer>
        </ContentContainer>
      </Main>
    </>
  );
};

export default HomePage;
